name: openim
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+1

environment:
  sdk: '>=2.19.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
<<<<<<< HEAD
  cupertino_icons: 1.0.5
  flutter_screenutil: 5.5.4
  get: 4.6.5
  shared_preferences: 2.0.15
  path_provider: 2.0.11
=======
<<<<<<< HEAD
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
>>>>>>> ed9233a1b555021c01446d5b388e0dd3d71a600d
  sprintf: 7.0.0
  rxdart: 0.27.5
  pin_code_fields: 7.3.0
  image_picker: 0.8.4+9
  dio: 4.0.6
  azlistview: 2.0.0
  lpinyin: 2.0.3
#  country_code_picker: 2.0.2
  country_picker: 2.0.19
  image_gallery_saver: 1.7.1
  flutter_easyloading: 3.0.5
  wechat_assets_picker: 7.3.1
  wechat_camera_picker: 3.2.0+1
  file_picker: 4.4.0
  open_file: 3.2.1
  permission_handler: 10.1.0
  mime_type: 1.0.0
  uuid: 3.0.6
  cached_network_image: 3.2.2
  lottie: 1.4.3
  qr_flutter: 4.0.0
  image_cropper: 2.0.3
  dotted_decoration: 2.0.0
  package_info_plus: 1.4.0
  search_keyword_text: ^0.0.2
  qr_code_scanner: 1.0.0
  pretty_dio_logger: 1.2.0-beta-1
  logger: 1.1.0
  animated_text_kit: 4.2.1
  flutter_local_notifications: 9.3.2
  flutter_app_badger: 1.3.0
  crypto: 3.0.1
  pull_to_refresh: 2.0.0
  url_launcher: 6.0.20
  sp_util: 2.0.3
  common_utils: 2.1.0
  uri_to_file: 0.2.0
  map_launcher: 2.2.1+1
  flutter_map: 0.14.0
  flutter_spinkit: 5.1.0
  percent_indicator: 4.2.2
  flutter_image_compress: 1.1.3
  app_installer: 1.1.0
  r_scan: 0.1.6+1
  collection: 1.17.0
  flutter_bugly: 0.4.4
  tencent_cos: 1.0.5
  flutter_cupertino_datetime_picker: 3.0.0
  device_info_plus: 6.0.0
  dart_date: ^1.1.1
  getuiflut: ^0.2.18
#  flutter_openim_widget: 2.3.0
  flutter_openim_widget:
    path: ../flutter_openim_widget
    # git:
    #   url: https://github.com/jjjachyty/flutter_openim_widget.git
    #   ref: master
  agora_rtc_engine:
    git:
      url: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK.git
      ref: main
  just_audio: ^0.9.32
  agora_rtm: ^1.5.0
<<<<<<< HEAD
  webview_flutter: ^4.4.1
=======
  package_info_plus: ^4.1.0
=======
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 5.0.2
  pretty_dio_logger: 1.3.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  shared_preferences: 2.0.18
  sprintf: 7.0.0
  uuid: 3.0.7
  flutter_bugly: 0.4.4
  path_provider: 2.0.13
  android_path_provider: 0.3.0
  image_picker: 0.8.7
  flutter_easyloading: 3.0.5
  azlistview: 2.0.0
  lpinyin: 2.0.3
  rxdart: 0.27.7
  permission_handler: 10.2.0
  flutter_slidable: 2.0.0
  wechat_assets_picker: 8.4.0
  wechat_camera_picker: 3.8.0
  extended_image: 7.0.2
  flutter_screenutil: 5.7.0
  country_picker: 2.0.20
  image_gallery_saver: 1.7.1
  file_picker: 5.2.6
  open_filex: 4.3.2
  lottie: 2.3.0
  qr_flutter: 4.1.0
  r_scan: 0.1.6+1
  qr_code_scanner: 1.0.1
  image_cropper: 3.0.1
  package_info_plus: 3.1.2
  search_keyword_text: 0.0.2
  animated_text_kit: 4.2.2
  flutter_local_notifications: 13.0.0
  flutter_app_badger: 1.5.0
  crypto: 3.0.2
  pull_to_refresh: 2.0.0
  url_launcher: 6.1.10
  common_utils: 2.1.0
  uri_to_file: 0.2.0
  map_launcher: 2.5.0+1
  flutter_map: 3.1.0
  flutter_spinkit: 5.1.0
  percent_indicator: 4.2.3
  flutter_image_compress: 1.1.3
  app_installer: 1.1.0
  collection:
  flutter_datetime_picker: 1.5.1
  font_awesome_flutter: 10.4.0
  dart_date: 1.1.1
  video_compress: 3.1.2
  just_audio: 0.9.31
  flutter_inappwebview: 5.7.2+3
  vibration: 1.7.6
  getuiflut: 0.2.18
  scroll_to_index: 3.0.1
  flutter_screen_lock: 9.0.1
  local_auth: 2.1.6
  local_auth_android: 1.0.21
  local_auth_ios: 1.1.1
  gesture_password_widget: 2.0.1
  sound_mode: 2.0.2
  device_info_plus: 8.1.0
  visibility_detector: 0.4.0+2
  rotated_corner_decoration: 2.1.0
  chat_listview: 0.0.2
  mime: 1.0.4
  flutter_download_manager:
    git:
      url: https://github.com/hrxiang/flutter_download_manager.git
  synchronized: 3.0.1
  pin_code_fields: 7.3.0
  flutter_openim_sdk: 3.1.0

  openim_common:
    path: openim_common

dependency_overrides:
  lottie: 2.3.0
  animate_do: 3.0.2
>>>>>>> 20248c558d5e13fd7fc35a425db26ae62f1cc068
>>>>>>> ed9233a1b555021c01446d5b388e0dd3d71a600d

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IconFontIcons
      fonts:
        - asset: assets/fonts/iconfont.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
